right_hand_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - hand_right_thumb_joint
    - hand_right_index_joint
    - hand_right_mrl_joint

  constraints:
    goal_time: &goal_time_constraint 0.6
    stopped_velocity_tolerance: &stopped_velocity_constraint 0.75
    hand_right_thumb_joint:
      goal: &hand_goal_pos_constraint 5.0
    hand_right_index_joint:
      goal: &index_goal_pos_constraint 5.0
    hand_right_mrl_joint:
      goal: *hand_goal_pos_constraint

  stop_trajectory_duration: 0.0

left_hand_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - hand_left_thumb_joint
    - hand_left_index_joint
    - hand_left_mrl_joint

  constraints:
    goal_time: *goal_time_constraint
    stopped_velocity_tolerance: *stopped_velocity_constraint
    hand_left_thumb_joint:
      goal: *hand_goal_pos_constraint
    hand_left_index_joint:
      goal: *index_goal_pos_constraint
    hand_left_mrl_joint:
      goal: *hand_goal_pos_constraint

  stop_trajectory_duration: 0.0
