torso_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - torso_1_joint
    - torso_2_joint

  constraints:
    goal_time: &goal_time_constraint 0.6
    stopped_velocity_tolerance: &stopped_velocity_constraint 0.05
    torso_1_joint:
      goal: &goal_pos_constraint 0.02
    torso_2_joint:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0

head_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - head_1_joint
    - head_2_joint

  constraints:
    goal_time: *goal_time_constraint
    stopped_velocity_tolerance: *stopped_velocity_constraint
    head_1_joint:
      goal: *goal_pos_constraint
    head_2_joint:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0

left_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint
  constraints:
    goal_time: *goal_time_constraint
    stopped_velocity_tolerance: *stopped_velocity_constraint
    arm_left_1_joint:
      goal: *goal_pos_constraint
    arm_left_2_joint:
      goal: *goal_pos_constraint
    arm_left_3_joint:
      goal: *goal_pos_constraint
    arm_left_4_joint:
      goal: *goal_pos_constraint
    arm_left_5_joint:
      goal: *goal_pos_constraint
    arm_left_6_joint:
      goal: *goal_pos_constraint
    arm_left_7_joint:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0

right_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - arm_right_1_joint
    - arm_right_2_joint
    - arm_right_3_joint
    - arm_right_4_joint
    - arm_right_5_joint
    - arm_right_6_joint
    - arm_right_7_joint
  constraints:
    goal_time: *goal_time_constraint
    stopped_velocity_tolerance: *stopped_velocity_constraint
    arm_right_1_joint:
      goal: *goal_pos_constraint
    arm_right_2_joint:
      goal: *goal_pos_constraint
    arm_right_3_joint:
      goal: *goal_pos_constraint
    arm_right_4_joint:
      goal: *goal_pos_constraint
    arm_right_5_joint:
      goal: *goal_pos_constraint
    arm_right_6_joint:
      goal: *goal_pos_constraint
    arm_right_7_joint:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0

right_hand_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - hand_right_thumb_joint
    - hand_right_index_joint
    - hand_right_mrl_joint

  constraints:
    goal_time: *goal_time_constraint
    stopped_velocity_tolerance: 0.75
    hand_right_thumb_joint:
      goal: &hand_goal_pos_constraint 0.3
    hand_right_index_joint:
      goal: 0.6
    hand_right_mrl_joint:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0

left_hand_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - hand_left_thumb_joint
    - hand_left_index_joint
    - hand_left_mrl_joint

  constraints:
    goal_time: *goal_time_constraint
    stopped_velocity_tolerance: 0.75
    hand_left_thumb_joint:
      goal: *hand_goal_pos_constraint
    hand_left_index_joint:
      goal: 0.6
    hand_left_mrl_joint:
      goal: *hand_goal_pos_constraint

  stop_trajectory_duration: 0.0

left_leg_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - leg_left_1_joint
    - leg_left_2_joint
    - leg_left_3_joint
    - leg_left_4_joint
    - leg_left_5_joint
    - leg_left_6_joint
  constraints:
    goal_time: *goal_time_constraint
    stopped_velocity_tolerance: *stopped_velocity_constraint
    leg_left_1_joint:
      goal: *goal_pos_constraint
    leg_left_2_joint:
      goal: *goal_pos_constraint
    leg_left_3_joint:
      goal: *goal_pos_constraint
    leg_left_4_joint:
      goal: *goal_pos_constraint
    leg_left_5_joint:
      goal: *goal_pos_constraint
    leg_left_6_joint:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0

right_leg_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - leg_right_1_joint
    - leg_right_2_joint
    - leg_right_3_joint
    - leg_right_4_joint
    - leg_right_5_joint
    - leg_right_6_joint
  constraints:
    goal_time: *goal_time_constraint
    stopped_velocity_tolerance: *stopped_velocity_constraint
    leg_right_1_joint:
      goal: *goal_pos_constraint
    leg_right_2_joint:
      goal: *goal_pos_constraint
    leg_right_3_joint:
      goal: *goal_pos_constraint
    leg_right_4_joint:
      goal: *goal_pos_constraint
    leg_right_5_joint:
      goal: *goal_pos_constraint
    leg_right_6_joint:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0
