{leg_left_1_joint: 0.0, leg_left_2_joint: 0.0, leg_left_3_joint: 0.0,
  leg_left_4_joint: 0.0, leg_left_5_joint: 0.0, leg_left_6_joint: -0.0,
  leg_right_1_joint: 0.0, leg_right_2_joint: 0.0, leg_right_3_joint: 0.0,
  leg_right_4_joint: 0.0, leg_right_5_joint: 0.0, leg_right_6_joint: 0.0}
